config/routes.rb
KariakooSales::Application.routes.draw do
  resources :market_types

  resources :units

  resources :qualities

  resources :price_receipt_units

  resources :locations

  resources :commodities

  resources :sales

  root :to => 'sales#index'

end

app/controllers/market_types_controller.rb
class MarketTypesController < ApplicationController
  # GET /market_types
  # GET /market_types.json
  def index
    @market_types = MarketType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @market_types }
    end
  end

  # GET /market_types/1
  # GET /market_types/1.json
  def show
    @market_type = MarketType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @market_type }
    end
  end

  # GET /market_types/new
  # GET /market_types/new.json
  def new
    @market_type = MarketType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @market_type }
    end
  end

  # GET /market_types/1/edit
  def edit
    @market_type = MarketType.find(params[:id])
  end

  # POST /market_types
  # POST /market_types.json
  def create
    @market_type = MarketType.new(params[:market_type])

    respond_to do |format|
      if @market_type.save
        format.html { redirect_to @market_type, notice: 'Market type was successfully created.' }
        format.json { render json: @market_type, status: :created, location: @market_type }
      else
        format.html { render action: "new" }
        format.json { render json: @market_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /market_types/1
  # PUT /market_types/1.json
  def update
    @market_type = MarketType.find(params[:id])

    respond_to do |format|
      if @market_type.update_attributes(params[:market_type])
        format.html { redirect_to @market_type, notice: 'Market type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @market_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /market_types/1
  # DELETE /market_types/1.json
  def destroy
    @market_type = MarketType.find(params[:id])
    @market_type.destroy

    respond_to do |format|
      format.html { redirect_to market_types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/market_types_helper.rb
module MarketTypesHelper
end

app/views/market_types/_form.html.erb
<%= form_for(@market_type) do |f| %>
  <% if @market_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@market_type.errors.count, "error") %> prohibited this market_type from being saved:</h2>

      <ul>
      <% @market_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/market_types/edit.html.erb
<h1>Editing market_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @market_type %> |
<%= link_to 'Back', market_types_path %>

app/views/market_types/index.html.erb
<h1>Mmarket Types</h1>

<table>
  <tr>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @market_types.each do |market_type| %>
  <tr>
    <td><%= market_type.value %></td>
    <td><%= link_to 'Show', market_type %></td>
    <td><%= link_to 'Edit', edit_market_type_path(market_type) %></td>
    <td><%= link_to 'Destroy', market_type, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Market type', new_market_type_path %>

app/views/market_types/new.html.erb
<h1>New market_type</h1>

<%= render 'form' %>

<%= link_to 'Back', market_types_path %>

app/views/market_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Value:</b>
  <%= @market_type.value %>
</p>


<%= link_to 'Edit', edit_market_type_path(@market_type) %> |
<%= link_to 'Back', market_types_path %>