config/routes.rb
KariakooSales::Application.routes.draw do
  resources :market_types

  resources :units

  resources :qualities

  resources :price_receipt_units

  resources :locations

  resources :commodities

  resources :sales

  root :to => 'sales#index'

end

app/models/price_receipt_unit.rb
class PriceReceiptUnit < ActiveRecord::Base
  attr_accessible :value
  belongs_to :sale

  validates :value, :presence => true, :length => { :in => 1..50 }
end

app/controllers/price_receipt_units_controller.rb
class PriceReceiptUnitsController < ApplicationController
  # GET /price_receipt_units
  # GET /price_receipt_units.json
  def index
    @price_receipt_units = PriceReceiptUnit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @price_receipt_units }
    end
  end

  # GET /price_receipt_units/1
  # GET /price_receipt_units/1.json
  def show
    @price_receipt_unit = PriceReceiptUnit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @price_receipt_unit }
    end
  end

  # GET /price_receipt_units/new
  # GET /price_receipt_units/new.json
  def new
    @price_receipt_unit = PriceReceiptUnit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @price_receipt_unit }
    end
  end

  # GET /price_receipt_units/1/edit
  def edit
    @price_receipt_unit = PriceReceiptUnit.find(params[:id])
  end

  # POST /price_receipt_units
  # POST /price_receipt_units.json
  def create
    @price_receipt_unit = PriceReceiptUnit.new(params[:price_receipt_unit])

    respond_to do |format|
      if @price_receipt_unit.save
        format.html { redirect_to @price_receipt_unit, notice: 'Price receipt unit was successfully created.' }
        format.json { render json: @price_receipt_unit, status: :created, location: @price_receipt_unit }
      else
        format.html { render action: "new" }
        format.json { render json: @price_receipt_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /price_receipt_units/1
  # PUT /price_receipt_units/1.json
  def update
    @price_receipt_unit = PriceReceiptUnit.find(params[:id])

    respond_to do |format|
      if @price_receipt_unit.update_attributes(params[:price_receipt_unit])
        format.html { redirect_to @price_receipt_unit, notice: 'Price receipt unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @price_receipt_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /price_receipt_units/1
  # DELETE /price_receipt_units/1.json
  def destroy
    @price_receipt_unit = PriceReceiptUnit.find(params[:id])
    @price_receipt_unit.destroy

    respond_to do |format|
      format.html { redirect_to price_receipt_units_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/price_receipt_units_helper.rb
module PriceReceiptUnitsHelper
end

app/views/price_receipt_units/_form.html.erb
<%= simple_form_for @price_receipt_unit, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :value %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                price_receipt_units_path, :class => 'btn' %>
  </div>
<% end %>

app/views/price_receipt_units/edit.html.erb
<%- model_class = @price_receipt_unit.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/price_receipt_units/index.html.erb
<%- model_class = PriceReceiptUnit.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:value) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @price_receipt_units.each do |price_receipt_unit| %>
      <tr>
        <td><%= link_to price_receipt_unit.id, price_receipt_unit_path(price_receipt_unit) %></td>
        <td><%= price_receipt_unit.value %></td>
        <td><%=l price_receipt_unit.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_price_receipt_unit_path(price_receipt_unit), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      price_receipt_unit_path(price_receipt_unit),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_price_receipt_unit_path,
            :class => 'btn btn-primary' %>

app/views/price_receipt_units/new.html.erb
<%- model_class = @price_receipt_unit.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/price_receipt_units/show.html.erb
<%- model_class = @price_receipt_unit.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:value) %>:</strong><br>
  <%= @price_receipt_unit.value %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              price_receipt_units_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_price_receipt_unit_path(@price_receipt_unit), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              price_receipt_unit_path(@price_receipt_unit),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>