config/routes.rb
KariakooSales::Application.routes.draw do
  resources :market_types

  resources :units

  resources :qualities

  resources :price_receipt_units

  resources :locations

  resources :commodities

  resources :sales

  root :to => 'sales#index'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  attr_accessible :commodity, :farmer_name, :location, :market_type, :price_receiptUnit, :price_received, :quality, :sale_date, :unit, :volume
  has_many :commodities
  has_many :locations
  has_many :market_types
  has_many :price_receiptUnits
  has_many :units
 
  validates :commodity, :presence => true
  validates :farmer_name, :presence => true
  validates :location, :presence => true
  validates :market_type, :presence => true
  validates :price_receiptUnit, :presence => true
  validates :price_received, :presence => true
  validates :quality, :presence => true
  validates :sale_date, :presence => true
  validates :unit, :presence => true
  validates :volume, :presence => true
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sales }
    end
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
    @sale = Sale.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sale }
    end
  end

  # GET /sales/new
  # GET /sales/new.json
  def new
    @sale = Sale.new
    #LOOKUP: @market_types = MarketType.all    
    #LOOKUP: @commodities = Commodity.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sale }
    end
  end

  # GET /sales/1/edit
  def edit
    @sale = Sale.find(params[:id])
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(params[:sale])

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render json: @sale, status: :created, location: @sale }
      else
        format.html { render action: "new" }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sales/1
  # PUT /sales/1.json
  def update
    @sale = Sale.find(params[:id])

    respond_to do |format|
      if @sale.update_attributes(params[:sale])
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy

    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= simple_form_for @sale, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :farmer_name %>
  <%= f.input :sale_date %>

  <%#= collection_select @sale, :market_type, @market_types, :value, :value %>
  
  <%#= f.association :markettypes, :collection => MarketType.all(:order => 'value') %>
  <%= f.input :market_type %>
  <%= f.input :location %>
  <%= f.input :volume %>
  <%= f.input :unit %>
  <%= f.input :quality %>
  <%#=collection_select @sale, :commodity, @commodities, :value, :value %>
  <%= f.input :commodity %>
  <%= f.input :price_received %>
  <%= f.input :price_receiptUnit %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sales_path, :class => 'btn' %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<%- model_class = @sale.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/sales/index.html.erb
<%- model_class = Sale.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:farmer_name) %></th>
      <th><%= model_class.human_attribute_name(:sale_date) %></th>
      <th><%= model_class.human_attribute_name(:market_type) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:volume) %></th>
      <th><%= model_class.human_attribute_name(:unit) %></th>
      <th><%= model_class.human_attribute_name(:quality) %></th>
      <th><%= model_class.human_attribute_name(:commodity) %></th>
      <th><%= model_class.human_attribute_name(:price_received) %></th>
      <th><%= model_class.human_attribute_name(:price_receiptUnit) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= link_to sale.id, sale_path(sale) %></td>
        <td><%= sale.farmer_name %></td>
        <td><%= sale.sale_date %></td>
        <td><%#= sale.market_type, :collection => [ "High", "Medium", "Low"]  %></td>
        <td><%= sale.location %></td>
        <td><%= sale.volume %></td>
        <td><%= sale.unit %></td>
        <td><%= sale.quality %></td>
        <td><%= sale.commodity %></td>
        <td><%= sale.price_received %></td>
        <td><%= sale.price_receiptUnit %></td>
        <td><%=l sale.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sale_path(sale), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      sale_path(sale),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sale_path,
            :class => 'btn btn-primary' %>

app/views/sales/new.html.erb
<%- model_class = @sale.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/sales/show.html.erb
<%- model_class = @sale.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:farmer_name) %>:</strong><br>
  <%= @sale.farmer_name %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:sale_date) %>:</strong><br>
  <%= @sale.sale_date %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:market_type) %>:</strong><br>
  <%= @sale.market_type %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:location) %>:</strong><br>
  <%= @sale.location %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:volume) %>:</strong><br>
  <%= @sale.volume %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:unit) %>:</strong><br>
  <%= @sale.unit %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:quality) %>:</strong><br>
  <%= @sale.quality %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:commodity) %>:</strong><br>
  <%= @sale.commodity %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:price_received) %>:</strong><br>
  <%= @sale.price_received %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:price_receiptUnit) %>:</strong><br>
  <%= @sale.price_receiptUnit %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              sales_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sale_path(@sale), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sale_path(@sale),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>